Extra checks design2
turbot/steampipe-mod-aws-compliance pull request #431
Opened 2022-06-29 14:48 UTC by rajlearner17

### Checklist
- [ ] Issue(s) linked

2022-07-05 14:45 UTC, cbruno10 requested changes
@rajlearner17 I know this PR is still in draft, but I took an initial look as I know we're releasing this week. Please see comments, if any are already changed, please disregard, thanks!

2022-07-05 14:45 UTC, cbruno10 commented on query/elb/elb_application_classic_network_lb_prohibit_public_access.sql
> +		arn,
@rajlearner17 Why is this query using tabs (along with others)?

2022-07-05 14:45 UTC, cbruno10 commented on other_checks/other.sp
> +  title         = "Other"
```suggestion
  title         = "Other Compliance Checks"
```

2022-07-06 08:00 UTC, misraved commented on query/eks/eks_cluster_control_plane_audit_logging_enabled.sql
> +    log -> 'Types'  as log_type
```suggestion
    log -> 'Types' as log_type
```

2022-07-06 08:00 UTC, misraved commented on query/eks/eks_cluster_control_plane_audit_logging_enabled.sql
> +    and (log -> 'Types') @> '["api","audit", "authenticator", "controllerManager","scheduler"]'
```suggestion
    and (log -> 'Types') @> '["api", "audit", "authenticator", "controllerManager", "scheduler"]'
```

2022-07-06 08:09 UTC, misraved commented on query/elb/elb_application_classic_lb_with_outbound_rule.sql
> +    else l.title || ' have outbound rule(s).'
Can we add how many outbound rules are present?

2022-07-06 08:12 UTC, misraved commented on query/elb/elb_listener_use_secure_ssl_cipher.sql
> + -- Required Columns
```suggestion
  -- Required Columns
```

2022-07-06 08:15 UTC, misraved commented on query/glue/glue_data_catalog_encryption_settings_password_encryption_enabled.sql
> +    when connection_password_encryption is not null and connection_password_encryption ->> 'ReturnConnectionPasswordEncrypted' != 'false' then 'enabled glue data catalog connection password encryptio
Please make changes as per the above suggestion

2022-07-06 08:16 UTC, misraved commented on query/glue/glue_dev_endpoint_s3_encryption_enabled.sql
> +    when e is not null and e ->> 'S3EncryptionMode' != 'DISABLED' then d.title || ' s3 encryption enabled.'
```suggestion
    when e is not null and e ->> 'S3EncryptionMode' != 'DISABLED' then d.title || ' S3 encryption enabled.'
```

2022-07-06 08:17 UTC, misraved commented on query/glue/glue_dev_endpoint_s3_encryption_enabled.sql
> +    else d.title || ' s3 encryption disabled.'
```suggestion
    else d.title || ' S3 encryption disabled.'
```

2022-07-06 08:19 UTC, misraved commented on query/iam/iam_policy_custom_no_assume_role.sql
> +    when fu.user_id is not null then u.name || ' custom policies allows STS Role assumption.'
```suggestion
    when fu.user_id is not null then u.name || ' custom policies allow STS Role assumption.'
```

2022-07-06 08:20 UTC, misraved commented on query/iam/iam_user_with_administrator_access_mfa_enabled.sql
> +    when au.user_id is not null and u.mfa_enabled then u.name || ' have MFA token enabled.'
```suggestion
    when au.user_id is not null and u.mfa_enabled then u.name || ' has MFA token enabled.'
```

2022-07-06 17:56 UTC, merged