Add [S3.12] S3 access control lists (ACLs) should not be used to manage user access to buckets. Closes #363
turbot/steampipe-mod-aws-compliance pull request #489
Opened 2022-08-24 05:11 UTC by vkumbha

### Checklist
- [ ] Issue(s) linked

2022-08-24 15:09 UTC, cbruno10 requested changes
@vkumbha Please see review, thanks!

2022-08-24 15:09 UTC, cbruno10 commented on foundational_security/s3.sp
> +control "foundational_security_s3_12" {
Please add this to the benchmark list above too

2022-08-25 12:35 UTC, cbruno10 approved these changes

2022-08-29 11:59 UTC, misraved commented on query/s3/s3_bucket_acls_should_prohibit_user_access.sql
> +   arn,
```suggestion
    -- Required Columns
  arn as resource,
```

2022-08-29 12:00 UTC, misraved commented on query/s3/s3_bucket_acls_should_prohibit_user_access.sql
> +   region,
```suggestion
  -- Additional Dimensions
   region, 
```

2022-08-29 12:35 UTC, misraved reviewed
Please make changes as per the suggestions.

2022-08-29 15:56 UTC, rajlearner17 approved these changes

2022-09-12 13:46 UTC, merged