Add/Update AWS Audit Manager > GxP 21 CFR Part 11 Closes #598
turbot/steampipe-mod-aws-compliance pull request #600
Opened 2023-04-03 13:38 UTC by madhushreeray30

### Checklist
- [ ] Issue(s) linked

2023-04-04 12:44 UTC, cbruno10 requested changes
@madhushreeray30 I left some comments, can you please have a look? Thanks!

2023-04-04 12:44 UTC, cbruno10 commented on gxp_21_cfr_part_11/gxp_21_cfr_part_11.sp
> +    benchmark.gxp_21_cfr_part_11_11_30,
@madhushreeray30 Why was this moved? In GxP's organization, does 11_11_30 come after 11_11_200?

2023-04-04 12:44 UTC, cbruno10 commented on gxp_21_cfr_part_11/11_200.sp
> +  description = "TO DO"
What is this supposed to be?

2023-04-04 13:48 UTC, cbruno10 commented on gxp_21_cfr_part_11/11_200.sp
> +  description = "TO DO"
Do we have any description we can use? Will the Hub page look blank/empty (assming we don't have a separate doc for this one)?

2023-04-07 09:38 UTC, misraved reviewed
Please take a look at the review comments. Thanks!!

2023-04-07 09:38 UTC, misraved commented on conformance_pack/codebuild.sp
> +  description = "This control checks if an CodeBuild project has encryption enabled for all of its artifacts. The rule is non compliant if 'encryptionDisabled' is set to 'true' for any primary or sec
```suggestion
  description = "This control checks if a CodeBuild project has encryption enabled for all of its artifacts. The rule is non compliant if 'encryptionDisabled' is set to 'true' for any primary or secondary (if present) artifact configurations."
```

2023-04-07 09:38 UTC, misraved commented on conformance_pack/opensearch.sp
> +  description = "This control check if Amazon OpenSearch Service nodes are encrypted end to end. The rule is non compliant if the node-to-node encryption is not enabled on the domain."
```suggestion
  description = "This control checks if Amazon OpenSearch Service nodes are encrypted end to end. The rule is non-compliant if the node-to-node encryption is not enabled on the domain."
```

2023-04-07 09:38 UTC, misraved commented on conformance_pack/s3.sp
> +    soc_2              = "true"
Please sort the tags.

2023-04-07 09:38 UTC, misraved commented on conformance_pack/s3.sp
> +  description = "This control checks that the access granted by the S3 bucket is restricted by any of the principals, federated users, service principals, IP addresses, or VPCs that you provide. The
```suggestion
  description = "This control checks that the access granted by the S3 bucket is restricted by any of the principals, federated users, service principals, IP addresses, or VPCs that you provide. The rule is non-compliant if a bucket policy is not present."
```
Should the description be updated to use non-compliant?

2023-04-07 09:38 UTC, misraved commented on conformance_pack/s3.sp
> +        when policy_std is null then title || ' policy not publicly accessable.'
```suggestion
        when policy_std is null then title || ' policy not publicly accessible.'
```

2023-04-07 09:38 UTC, misraved commented on conformance_pack/s3.sp
> +        when s ->> 'Effect' = 'Allow' and (s -> 'Principal' -> 'AWS' = '["*"]' or s ->> 'Principal' = '*') then title || ' policy publicly accessable.'
```suggestion
        when s ->> 'Effect' = 'Allow' and (s -> 'Principal' -> 'AWS' = '["*"]' or s ->> 'Principal' = '*') then title || ' policy publicly accessible.'
```

2023-04-07 09:38 UTC, misraved commented on conformance_pack/s3.sp
> +        else title || ' policy not publicly accessable.'
```suggestion
        else title || ' policy not publicly accessible.'
```

2023-04-07 09:38 UTC, misraved commented on conformance_pack/vpc.sp
> +  description = "This control checks whether the vpc security groups that are in use allow unrestricted incoming traffic. Optionally the rule checks whether the port numbers are listed in the authori
```suggestion
  description = "This control checks whether the VPC security groups that are in use allow unrestricted incoming traffic. Optionally the rule checks whether the port numbers are listed in the authorizedTcpPorts parameter. The default values for authorizedTcpPorts are 80 and 443."
```

2023-04-07 11:01 UTC, misraved approved these changes

2023-04-07 11:01 UTC, merged