Add/Update AWS Audit Manager > PCI DSS V321 controls . Closes #624
turbot/steampipe-mod-aws-compliance pull request #626
Opened 2023-05-15 19:09 UTC by Priyanka-Chatterjee-2000

2023-05-18 12:43 UTC, rajlearner17 approved these changes
LGTM after testing and validating controls as per tracker

2023-05-19 11:16 UTC, madhushreeray30 requested changes
@Priyanka-Chatterjee-2000 There is a minor change please look at the comment. Thanks !

2023-05-19 11:40 UTC, madhushreeray30 approved these changes
LGTM.

2023-05-19 12:41 UTC, misraved approved these changes

2023-05-19 12:41 UTC, merged