Add/Update AWS Audit Manager > HIPAA Final Omnibus Security Rule 2013 controls. Closes #621
turbot/steampipe-mod-aws-compliance pull request #632
Opened 2023-05-25 05:57 UTC by Priyanka-Chatterjee-2000

### Checklist
- [ ] Issue(s) linked

2023-05-26 10:32 UTC, khushboo9024 commented on hipaa_final_omnibus_security_rule_2013/164_314/164_314_b_1.sp
> +    control.vpc_configured_to_use_vpc_endpoints
Please remove tag `hipaa_final_omnibus_security_rule_2013 = "true"` from control and please validate for other removed controls as well.

2023-05-26 10:33 UTC, khushboo9024 commented on hipaa_final_omnibus_security_rule_2013/164_314/164_314_b_2.sp
> +    control.vpc_configured_to_use_vpc_endpoints
@Priyanka-Chatterjee-2000 Please add tag `hipaa_final_omnibus_security_rule_2013 = "true"` to the control and check for other added controls as well.

2023-05-30 14:16 UTC, madhushreeray30 requested changes
@Priyanka-Chatterjee-2000 please look at the review comments, thanks!

2023-05-30 14:16 UTC, madhushreeray30 commented on conformance_pack/cloudtrail.sp
> +    nist_csf                               = "true"
```suggestion
    gdpr     = "true"
    nist_csf = "true"
```

2023-05-30 14:16 UTC, madhushreeray30 commented on hipaa_final_omnibus_security_rule_2013/164_314/164_314_b_1.sp
please add `hipaa_final_omnibus_security_rule_2013 = "true"` tag for control `vpc_configured_to_use_vpc_endpoints`

2023-05-30 14:16 UTC, madhushreeray30 commented
@Priyanka-Chatterjee-2000 please resolve the merge conflits.

2023-05-31 10:48 UTC, madhushreeray30 approved these changes
LGTM 👍

2023-05-31 13:50 UTC, misraved approved these changes

2023-05-31 13:51 UTC, merged