IAM.sp contains redundant controls closes #738
turbot/steampipe-mod-aws-compliance pull request #739
Opened 2023-12-19 06:45 UTC by khushboo9024

### Checklist
- [ ] Issue(s) linked

2024-01-09 19:17 UTC, cbruno10 requested changes
@khushboo9024 Please see review comments, thanks!

2024-01-10 07:05 UTC, khushboo9024 commented on conformance_pack/iam.sp
> -control "iam_account_password_policy_strong" {
May be config rule default values changed, we replaced this control for all our audit manager based benchmarks but we missed to update  for GDPR, FFIEC and cisa_cyber_essentials(non audit manager benchmarks) as these benchmarks are not checked in our monthly check.

2024-01-10 07:08 UTC, khushboo9024 commented on conformance_pack/iam.sp
> -control "iam_account_password_policy_strong" {
We are using `iam_account_password_policy_strong_min_reuse_24` as the replacement control. This control matches exactly with aws config rule [iam-password-policy](https://docs.aws.amazon.com/config/latest/developerguide/iam-password-policy.html).

2024-01-10 07:24 UTC, khushboo9024 commented on conformance_pack/iam.sp
> +        else 'Password policy ' ||
I've updated the reason to make it clearer and help avoid any misunderstanding for the user
And also this message is updated for all password policy controls, namely `iam_account_password_policy_strong_min_reuse_24` and `iam_account_password_policy_strong_min_length_8`

2024-01-12 05:36 UTC, cbruno10 commented on conformance_pack/iam.sp
> +        else 'Password policy ' ||
@khushboo9024 Can you please share a few screenshots of what the reasons look like when you run the control and it goes to alarm?

2024-01-12 05:38 UTC, cbruno10 commented on conformance_pack/iam.sp
> -control "iam_account_password_policy_strong" {
@khushboo9024 Does that reuse_24 control match the exact checks this removed control also had?

2024-01-15 06:31 UTC, khushboo9024 commented on conformance_pack/iam.sp
> +        else 'Password policy ' ||
<img width="1350" alt="image" src="https://github.com/turbot/steampipe-mod-aws-compliance/assets/46913995/65826886-bb23-4f95-a039-9d74b4f73fea">

2024-01-15 06:37 UTC, khushboo9024 commented on conformance_pack/iam.sp
> -control "iam_account_password_policy_strong" {
`iam_account_password_policy_strong_min_reuse_24` control is a superset of removed control(iam_account_password_policy_strong). Removed control was getting used as config([iam-password-policy](https://docs.aws.amazon.com/config/latest/developerguide/iam-password-policy.html) rule control which was wrong, we have not replaced is with `iam_account_password_policy_strong_min_reuse_24` control.

2024-01-23 13:59 UTC, cbruno10 approved these changes

2024-01-23 14:12 UTC, merged